version: '3'

services:

  nginx:
    image: nginx:1.13.3
    volumes:
      - .:/app
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - node

  node:
    image: node:13.6.0
    volumes:
      - node-sync:/app:nocopy
      - ./log:/tmp/logs
    working_dir: /app
    command: sh -c 'npm install; npm install -g nodemon; npm run dev'
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - .:/host
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: database

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 6065:80
    environment:
      PMA_HOST: mysql

volumes:
  node-sync:
    external: true