version: '2'
services:

  nginx:
    image: nginx:1.13.3
    volumes:
      - .:/app
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - node1

  node1:
    image: node:8.4.0
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'npm install -g nodemon ; npm run test'
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - rabbitmq
      - mailcatcher
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASS: 123

  mysql:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - .:/host
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080